events {}

http {
    server {
        listen 443 ssl;

        ssl_certificate     /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        root /usr/share/nginx/html;

        location / {
            sub_filter_once off;
            sub_filter "{{PORT}}" $server_port;
            index index.html;
        }
    }
}